# Generated by Django 3.1.7 on 2021-03-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CutLink',
        ),
    ]
