# Generated by Django 3.1.7 on 2021-03-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkcut', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutlink',
            options={'verbose_name': 'Ссылку', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
