# Generated by Django 3.1.7 on 2021-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkcut', '0004_auto_20210320_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutlink',
            name='short_link',
        ),
        migrations.AddField(
            model_name='cutlink',
            name='slug',
            field=models.SlugField(default='', max_length=20, verbose_name='Коротко о главном'),
        ),
    ]
