# Generated by Django 3.1.7 on 2021-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkcut', '0005_auto_20210321_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutlink',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='Коротко о главном'),
        ),
    ]
